// “I LIKE MY TRAINER. I LIKE THE LOOK OF THE STUDIO. I LIKE THE PEOPLE WHO USE IT. I LIKE THE MIX OF THOSE PEOPLE.”

// ― PAMELA, CAMBRIDGE

 
// “ITS A VERY CLEAN, LOW KEY GYM. FOR ME IT IS CLOSE TO WORK AND I LIKE THE CROWD.”

// ― NAOMI, CAMBRIDGE

 
// “HIGH QUALITY, DIVERSE GROUP CLASSES; EQUIPMENTS IN GOOD CONDITION; PEOPLE ARE NICE TO ONE ANOTHER LIKE IN A FRIENDLY COMMUNITY ”

// ― XIAOMU, CAMBRIDGE

 
// “CONVENIENTLY LOCATED GOOD AESTHETICS PLENTY OF ROOMS ― DOWNSTAIRS, WOMEN’S ROOM AND CLASSROOM SPACE LOW KEY”

// ― DEBORAH, CAMBRIDGE

 
// “CLUB IS CLEAN AND WELL KEPT. GROUP TRAINERS ARE ENTHUSIASTIC, ENGAGING AND WELL PREPARED. I LOVE THAT YOU HAVE ‘MORE MATURE’ TRAINERS... MAKES FOR GREAT ROLE MODELS”

// ― ARIANE, CAMBRIDGE

 
// “RUBBER BANDS FOR HAIR. WOMEN’S BATHROOM ON MAIN FLOOR. GOOD MACHINE S AND FRIENDLY STAFF.”

// ― LYNN, CAMBRIDGE

 
// “YOU HAVE EVERYTHING ONE COULD WANT IN A GYM AS WELL AS A GREAT LOCATION, GREAT STAFF, GREAT OWNER!”

// ― THOMAS, CAMBRIDGE

 
// “GREAT SELECTION OF EQUIPMENT FRIENDLY STAFF PARKING!”

// ― FRANK, CAMBRIDGE

 
// “FRIENDLY STAFF GREAT TRAINERS ― JASON IS TERRIFIC WOMEN’S GYM CLEAN FACILITIES GREAT HOURS GOOD COMMUNICATION RE: HOLIDAYS & INCLEMENT WEATHER PARKING”

// ― MUNIRA, CAMBRIDGE

 
// “CLEAN SPACE, UPDATED EQUIPMENT, EASY PARKING, NICE LOCKER ROOM, GREAT STAFF.”

// ― STEPHANIE, CAMBRIDGE

 
// “EQUIPMENT. ATMOSPHERE. HOURS. STAFF. ”

// ― WILLIAM, CAMBRIDGE

 
// “EASE OF PARKING. AVAILABILITY OF MACHINES I LIKE TO WORK WITH.FRIENDLINESS OF RECEPTION STAFF. EXCELLENT PTS.”

// ― ROBERT, CAMBRIDGE

 
// “CLEAN”

// ― TODD, CAMBRIDGE

 
// “YOUR EXTENSIVE DIVERSITY OF EQUIPMENT TYPES, THOUGH WISH YOU HAD A SEATED CALF PRESS.”

// ― JASON, CAMBRIDGE

 
// “GREAT HOURS, LOW COST, LOTS OF EQUIPMENT”

// ― ANTHONY, FRAMINGHAM

 
// “FRIENDLY STAFF AND LOTS OF VARIED EQUIPMENT TO WORK OUT ON. I HAVE BEEN COMING TO THIS GYM FOR 20 YRS!”

// ― DAVID, FRAMINGHAM

 
// “NICE CLIENTELE ”

// ― DAVID, FRAMINGHAM

 
// “INSTRUCTORS FOR THE VARIOUS CLASSES ARE GOOD. MANY CARDIO MACHINES AVAILABLE GOOD WEIGHT ROOM”

// ― RENEE, FRAMINGHAM

 
// “ALWAYS CLEAN AND EVERYONE IS ALWAYS SO NICE ”

// ― JEREMY, FRAMINGHAM

 
// “JENNA WAS REALLY GREAT AS A TRAINER. VERY UPBEAT. NOT OVERCROWDED AND GOOD MACHINES.”

// ― JACKIE, CAMBRIDGE

 
// “CLEAN AND NEAT. GREAT PERSONAL TRAINERS, ESPECIALLY DANA.”

// ― SALLY, FRAMINGHAM

 
// “YOU HAVE GREAT FITNESS CLASSES LIKE ZUMBA AND BODY FLOW AND PUMP. I LOVE THE INSTRUCTORS TOO. THEY HAVE SUCH PASSION AND ENERGY FOR WHAT THEY DO!”

// ― SHARON, CAMBRIDGE

 
// “IT HAS EVERYTHING I NEED FOR A WORKOUT AND IT IS CLOSE TO MY HOME”

// ― RAYMOND, FRAMINGHAM

 
// “BABYSITTING, CLASSES, WOMEN’S ROOM, AND THE CULTURE OF THE CLIENTS AND STAFF. SUCH A FUN FRIENDLY BUT STRONG WORKOUT ENVIRONMENT”

// ― ELIZABETH, CAMBRIDGE